### ISSUE TITLE
        if (statusArr[index].type == 0) {type = "Playing";}

### ISSUE THREAD

**Issue by SorinCR** [zapteryx/Zap#6] opened 2019-07-16 08:36 UTC
Happens when you try to change the status of the bot with the status command.

`TypeError: Cannot read property 'type' of undefined
    at Object.module.exports.actions (C:\Users\xxsor\Desktop\Zap-master\modules\base.js:126:30)
    at Timeout._onTimeout (C:\Users\xxsor\Desktop\Zap-master\bot.js:189:18)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)`

**Comment by zapteryx** [comment] 2019-07-16 11:21
Haven't actually experienced this before, I'll check on it and get back to you later.

**Comment by zapteryx** [comment] 2019-07-16 12:54
I can't reproduce this right now. Not sure if it was fixed in my current code, but I'll push it and see if it helps. Do let me know more elaborate steps on how to reproduce this issue.

**Comment by zapteryx** [comment] 2019-07-16 13:01
Reopen if this is still an issue

**Closed as completed by zapteryx** 2019-07-16 13:01 UTC
Labels: 1: bug, 2: invalid
