### ISSUE TITLE
"status": [] can't be empty.

### ISSUE THREAD

**Issue by SorinCR** [zapteryx/Zap#5] opened 2019-07-16 08:09 UTC
It's actually because it tries to load the status list but because there aren't any statuses it just can't do anything.
It's undefined

**Comment by zapteryx** [comment] 2019-07-16 12:51
I couldn't reproduce this because I was dumb and forgot that I fixed this, just that I hadn't committed and pushed.

**Closed as completed** 2019-07-16 13:00 UTC
Labels: 1: bug, 2: confirmed, 3: done
